### ISSUE TITLE
Typos found in local/chain/run_ctdnn_sa.sh

### ISSUE THREAD

**Issue by jhuang448** [emirdemirel/ALTA#1]
https://github.com/emirdemirel/ALTA/blob/fcbb8380d0e46f3721938b1b8d5fb5f6611f4611/s5/local/chain/run_ctdnn_sa.sh#L118
Remove the backslash
https://github.com/emirdemirel/ALTA/blob/fcbb8380d0e46f3721938b1b8d5fb5f6611f4611/s5/local/chain/run_ctdnn_sa.sh#L128
--testsets -> test_sets
https://github.com/emirdemirel/ALTA/blob/fcbb8380d0e46f3721938b1b8d5fb5f6611f4611/s5/local/chain/run_ctdnn_sa.sh#L175
--test_sets-- -> test_sets

**Comment by emirdemirel** [comment]
Typo fixed in the main branch.
