### ISSUE TITLE
usage: steps/align_fmllr.sh <data-dir> <lang-dir> <src-dir> <align-dir>

### ISSUE THREAD

**Issue by jhuang448** [emirdemirel/ALTA#2]
https://github.com/emirdemirel/ALTA/blob/fcbb8380d0e46f3721938b1b8d5fb5f6611f4611/s5/local/chain/run_ctdnn_sa.sh#L173-L176

Console log:

train
local/nnet3/run_alignment_gmm_sp.sh --stage 10 --nj 30 --train_set train --test_sets dev test --gmm_dir exp/tri3b --ali_dir exp/tri3b_ali_train_sp --lat_dir exp/chain_cleaned/tri3b_train_sp_lats
local/nnet3/run_alignment_gmm_sp.sh: aligning with the perturbed low-resolution data
steps/align_fmllr.sh --nj 30 --cmd run.pl --max-jobs-run 3 --beam 40 --retry_beam 500 data/train_sp data/lang
usage: steps/align_fmllr.sh <data-dir> <lang-dir> <src-dir> <align-dir>
e.g.:  steps/align_fmllr.sh data/train data/lang exp/tri1 exp/tri1_ali
main options (for others, see top of script file)
  --config <config-file>                                                   # config containing options
  --nj <nj>                                                                         # number of parallel jobs
  --use-graphs true                                                         # use graphs in src-dir
  --cmd (utils/run.pl|utils/queue.pl <queue opts>)      # how to run jobs.
  --fmllr-update-type (full|diag|offset|none)               # default full.

**Comment by emirdemirel** [comment]
Somehow some variables are not parsed. I have included them as default in local/nnet3/run_alignment_gmm_sp.sh .
